name: PROD - Build & Push GCR

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

env:
  IMAGE: europe-west4-docker.pkg.dev/grp-prd-fred-prj-clienteling/apps/stocks
  GCP_PROJECT_ID: grp-prd-fred-prj-clienteling
  REGISTRY_HOSTNAME: europe-west4-docker.pkg.dev
  GCP_CREDS: ${{ secrets.GCREDS_CICD_SA_FRED_PROD }}

jobs:
  build-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download and Configure gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: '333.0.0'
          service_account_key: ${{ env.GCP_CREDS }}
          project_id: ${{ env.GCP_PROJECT_ID }}
          export_default_credentials: true

      # Configure docker to use the gcloud command-line tool as a credential helper
      - name: Login to GCR registry
        run: |
          gcloud auth configure-docker ${{ env.REGISTRY_HOSTNAME }}

      # Required by docker/build-push-action@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Create docker tag prefix
      # We have to create a sortable docker tag to allow flux2 to dynamically find and update manifests with the latest version.
      - name: Docker tag prefix
        id: docker-tag
        run: |
          echo ::set-output name=image-tag::${GITHUB_REF#refs/*/}

      # Build the Docker image
      # We add github.run_number at the end of the tag because this ID is incrementable and allow fluxCD to sort the images to find the latest one.
      # https://github.com/fluxcd/flux2/blob/6416673c3079958adc6ceb2d7d14a729176d410f/docs/guides/sortable-image-tags.md
      - name: Build and publish container image with tag
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile
          tags: |
            ${{ env.IMAGE }}:${{ steps.docker-tag.outputs.image-tag }}
