name: Standard checks

on:
  pull_request:
    paths:
      - '**'
  workflow_dispatch:

env:
  CLIENTELING_GITHUB_TOKEN: ${{ secrets.CLIENTELING_GITHUB_TOKEN }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
          token: ${{ env.CLIENTELING_GITHUB_TOKEN }}

      - uses: jgierer12/npm-auth-gpr@v1
        with:
          token: ${{ env.CLIENTELING_GITHUB_TOKEN }}

      - name: npm install
        run: npm ci

      - name: npm build
        run: npm run build

      - name: lint
        run: npm run lint
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
          token: ${{ env.CLIENTELING_GITHUB_TOKEN }}

      - uses: jgierer12/npm-auth-gpr@v1
        with:
          token: ${{ env.CLIENTELING_GITHUB_TOKEN }}

      - name: npm install
        run: npm ci

      - name: npm build
        run: npm run build

      - name: test
        run: npm run test
